baseURL = "https://seraphinush-gaming.github.io/ktera-patch-notes/"
title = "K TERA patch note translations | seraphinush"

languageCode = "en-us"
publishDir = "docs"
theme = "hugo-notepadium"

[markup.highlight]
codeFences = true
noClasses = false

[params]
style = "dark"
dateFormat = "Monday, January 2, 2006"
logo = ""

[params.nav]
showCategories = true
showTags = true

[[params.nav.custom]]
  title = "About"
  url = "/about"
[[params.nav.custom]]
  title = "Patch Notes"
  url = "/categories/patch-notes"
[[params.nav.custom]]
  title = "Dev Posts"
  url = "/categories/dev-notes"
[[params.nav.custom]]
  title = "Youtube"
  url = "https://www.youtube.com/c/seraphinush-gaming"


[taxonomies]
category = "categories"
tag = "tags"