baseURL = "https://seraphinush-gaming.github.io/ktera-patch-notes/"
title = "K TERA patch note translations | seraphinush"

languageCode = "en-us"
publishDir = "docs"
theme = "hugo-notepadium"

[markup.highlight]
codeFences = true
noClasses = false

[params]
style = "dark"
dateFormat = "Monday, January 2, 2006"
logo = ""
license = "MIT License"
