title = "mysterium"
baseURL = "https://seraphinush-gaming.github.io/mysterium/"
publishDir = "docs"
languageCode = "en-us"
theme = "hugo-mysterium"

[params]
description = "blog by seraphinush"
dateFormat = "Monday, January 2, 2006"
trackingId = "UA-66500356-2"
adsenseId = "ca-pub-3598595244893452"
faviconUrl = "https://github.com/seraphinush-gaming/mysterium/blob/master/content/favicon.png?raw=true"
donateUrl = "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MPKFVY9JT7Z3A&source=url"

[[params.nav]]
  title = "about"
  url = "/about"
[[params.nav]]
  title = "lucidity"
  url = "/lucidity"
[[params.nav]]
  title = "youtube"
  url = "https://www.youtube.com/c/seraphinush-gaming?sub_confirmation=1"
[[params.nav]]
  title = "twitch"
  url = "https://www.twitch.tv/seraphinush"