title = "mysterium"
baseURL = "https://seraphinush-gaming.github.io/mysterium/"
publishDir = "docs"
languageCode = "en-us"
theme = "hugo-mysterium-theme"

[params]
description = "blog by seraphinush"
dateFormat = "Monday, January 2, 2006"
trackingId = "UA-66500356-2"
adsenseId = ""

[[params.nav]]
  title = "about"
  url = "/about"
[[params.nav]]
  title = "lucidity"
  url = "/lucidity"
[[params.nav]]
  title = "youtube"
  url = "https://www.youtube.com/c/seraphinush-gaming?sub_confirmation=1"
[[params.nav]]
  title = "twitch"
  url = "https://www.twitch.tv/seraphinush"